### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by sharpenedblade** [yllan/JXLook#21]
As compiling requires a developer certificate, I think you should make a release. There is thumbnail support now, so not releasing means people cannot use the new feature.

**Comment by ghost** [comment]
Let's see what comes first. The 2-year awaited release of JXLook 0.1.5. Or the JPEG XL support in macOS Sonoma pre-announced today:

[macOS 14 will support JPEG XL](https://news.ycombinator.com/item?id=36202088)

**Comment by sharpenedblade** [comment]
> Let's see what comes first. The 2-year awaited release of JXLook 0.1.5. Or the JPEG XL support in macOS Sonoma pre-announced today:
> 
> [macOS 14 will support JPEG XL](https://news.ycombinator.com/item?id=36202088)

This is too late, chrome and firefox already dropped jpeg XL support, so its not going anywhere. Also we could always compile from source with a $99 apple developer license

**Comment by low-batt** [comment]
An Apple developer license is **not** required to build JXLook. More on that below…

#### Firefox

As I am a Firefox user, this caught my attention:
> firefox already dropped jpeg XL support

The Internet is confused about this due to people testing JPEG XL images with the released version of Firefox. From [Experimental features in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#webrtc_and_media):
> Note that, as shown below, the feature is only available on Nightly builds (irrespective of whether the preference is set).

The preference referred to is `image.jxl.enabled` which is set to `false` by default, including in Nightly builds. I suspect that note was added due to people setting that preference to `true` in other builds of Firefox and concluding JPEG XL support is broken or dropped.

The Firefox bug tracking this is [Implement support for JPEG XL (image/jxl)](https://bugzilla.mozilla.org/show_bug.cgi?id=1539075), which is still open. Recently the keyword `parity-safari` was added.

Another consideration is web standards. Back in January, Mozilla [concluded that we are neutral on JPEG-XL](https://github.com/mozilla/standards-positions/issues/522#issuecomment-1409539985).

To be certain I was not providing incorrect information I downloaded the latest [Firefox Nightly](https://www.mozilla.org/en-US/firefox/118.0a1/releasenotes/) build, set the above preference to true and opened a JPEG XL image. Screenshot attached at the bottom of this comment.

My own conclusion is that Firefox has _not_ dropped support and is watching on the sidelines, waiting to see which new image format gets adopted.

#### Chrome

Indeed Chrome has pulled support for JPEG XL over lots of objections.

On August 7<sup>th</sup> Phoronix posted [Google May Reconsider JPEG-XL Image Support Within Chrome](https://www.phoronix.com/news/Chrome-JPEG-XL-Seconds). 

I would think it would take a lot for Chrome to reverse course.

#### macOS

Of course the recent interesting news is this from the [Safari Technology Preview 173 Release Notes](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-173#Overview):
> **JPEG XL** support on macOS Sonoma adds a new image format with an improved compression algorithm for better image quality at smaller file sizes than JPEG, but with the same progressive loading capability.

#### JXLook

I'm not running the macOS Sonoma Beta, but from what I've read it is looking like the need for JXLook will be going away due to the native support in macOS. Nonetheless there are people in the world who are trapped running older versions of macOS. If use of JPEG XL picks up they would benefit from JXLook.

The open JXLook pull request #27 contains various enhancements such as updating [libjxl](https://github.com/libjxl/libjxl) to v0.82.0 and support for HDR including enabling EDR. See that PR for details.

I too ran into the problem with the Xcode build failing due to certificate signing. This is still true with the above PR as I preserved the existing Xcode project settings.

To get the build to work change the `Signing Certificate` Xcode setting from `Development` to `Sign to Run Locally` in all three projects as shown here:

![jxlook-sigjning](https://github.com/yllan/JXLook/assets/86170219/9124e230-50c4-4d2e-879e-1d9472cb1866)

This is how I pulled the PR for that test:
<details>
<summary><b>Cloning and checking out PR:</b></summary>

```text
low-batt@gag jxlook-signing$ git clone git@github.com:yllan/JXLook.git
Cloning into 'JXLook'...
remote: Enumerating objects: 808, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 808 (delta 40), reused 40 (delta 40), pack-reused 764
Receiving objects: 100% (808/808), 13.11 MiB | 10.47 MiB/s, done.
Resolving deltas: 100% (413/413), done.
low-batt@gag jxlook-signing$ cd JXLook/
low-batt@gag JXLook (main=)$ gh pr checkout 27
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 58 (delta 21), reused 21 (delta 21), pack-reused 34
Unpacking objects: 100% (58/58), 3.39 MiB | 3.04 MiB/s, done.
From github.com:yllan/JXLook
 * [new ref]         refs/pull/27/head -> hdr
Switched to branch 'hdr'
low-batt@gag JXLook (hdr)$ 
```
</details>

The latest Firefox Nightly build displaying a JPEG XL screenshot I made from [Big Buck Bunny](https://www.youtube.com/watch?v=aqz-KE-bpKQ):

![firefox-nightly](https://github.com/yllan/JXLook/assets/86170219/edb92217-8dcd-40f9-9325-7cb3c705a8e1)
